FROM fedora:32 AS builder

RUN dnf install -y git-core gcc unbound-devel openssl-devel libcap-ng-devel \
	autoconf automake libtool make python3

ARG OVSREPO=https://github.com/openvswitch/ovs.git
ARG OVSBRANCH=master
ARG OVNREPO=https://github.com/ovn-org/ovn.git
ARG OVNBRANCH=main
ARG CFLAGS="-g -O2"

VOLUME ["/gitcache"]

WORKDIR /root
RUN git clone --reference-if-able /gitcache/ovs.git $OVSREPO
RUN git clone --reference-if-able /gitcache/ovn.git $OVNREPO

WORKDIR /root/ovs
RUN git checkout $OVSBRANCH && ./boot.sh && \
    ./configure --prefix=/opt --localstatedir=/var --sysconfdir=/etc CFLAGS="$CFLAGS" && \
    make -j4 && \
    make install

WORKDIR /root/ovn
RUN git checkout $OVNBRANCH && ./boot.sh && \
    ./configure --prefix=/opt --localstatedir=/var --sysconfdir=/etc CFLAGS="$CFLAGS" \
        --with-ovs-source=/root/ovs && \
    make -j4 && \
    make install

WORKDIR /root

RUN dnf install -y unbound openssl libcap-ng jq hostname && dnf clean all && rm -rf /var/cache/dnf

# We explicitly disable log output to file, but nevertheless we fail to startup
# if the files don't exist.
RUN /bin/bash -c 'mkdir -p /var/log/ovn; \
                  touch /var/log/ovn/ovsdb-server-{n,s}b.log; \
                  chown -R 1000:1000 /var/log/ovn'

RUN /bin/bash -c 'mkdir -p /var/lib/openvswitch; \
		  chown -R 1000:1000 /var/lib/openvswitch'

RUN /bin/bash -c 'mkdir -p /etc/ovn; \
                  chown -R 1000:1000 /etc/ovn'

COPY image-env.sh /
COPY scripts/* /

VOLUME ["/var/lib/openvswitch", "/ovn-run"]

USER 1000:1000
